/**
******************************************************
***  Class Name: CarGUI.
***  Class Author:  Chris Lorenzo
******************************************************
* This class serves as the GUI to create and use
* objects from the car class
******************************************************
*** Date: 13 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
package Lorenzo_Project1_ObjClsAttMeth;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author HR1
 */
public class CarGUI extends javax.swing.JFrame {

    /**
     * Creates new form CarGUI
     */
    public CarGUI() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        btnCreateCar = new javax.swing.JButton();
        lblStatusMsg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGas = new javax.swing.JButton();
        btnBrake = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOY RIDE - THE GAME");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("Joy Ride");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Create a car:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Make:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Model:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Color:");

        txtName.setNextFocusableComponent(txtMake);

        txtMake.setNextFocusableComponent(txtModel);

        txtModel.setNextFocusableComponent(txtColor);

        txtColor.setNextFocusableComponent(btnCreateCar);

        btnCreateCar.setText("Create Car");
        btnCreateCar.setNextFocusableComponent(btnGas);
        btnCreateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCarActionPerformed(evt);
            }
        });
        btnCreateCar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCreateCarKeyPressed(evt);
            }
        });

        lblStatusMsg.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        lblStatusMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusMsg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Current Speed:");

        lblSpeed.setFont(new java.awt.Font("Tahoma", 0, 80)); // NOI18N
        lblSpeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpeed.setText("0");
        lblSpeed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("mph");

        btnGas.setBackground(new java.awt.Color(0, 204, 51));
        btnGas.setText("Accelerate");
        btnGas.setEnabled(false);
        btnGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGasActionPerformed(evt);
            }
        });

        btnBrake.setBackground(new java.awt.Color(255, 0, 0));
        btnBrake.setText("Brake");
        btnBrake.setEnabled(false);
        btnBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrakeActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Your Car:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Name:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Make:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Model:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Color:");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMake.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatusMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(lblSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(6, 6, 6)))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCreateCar)
                                        .addGap(4, 4, 4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(80, 80, 80)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblMake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(lblColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMake, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreateCar)
                            .addComponent(btnGas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblStatusMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
******************************************************
***  Method Name: btnCreateCarActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method is responsible for taking the input value
*   from the user, converting them in String vars and then
*   sending those var to the Car's constructor as param values.
*   If successful, Car object is made, values are placed into
*   profile labels, input boxes are cleared, create button
*   is disabled, and brake and acceleration buttons are enabled.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
    
    private void btnCreateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCarActionPerformed
        // TODO add your handling code here:
        //Place user input into vars to instantiate a new Car object
        name = txtName.getText();
        make = txtMake.getText();
        model = txtModel.getText();
        color = txtColor.getText();

        if(name.length() > 0 && make.length() > 0 && model.length() > 0 && color.length() > 0)
        {
            try
            {   
                userCar = new Car(name, make, model, color);
                userPresent = true;
            }
            catch (NumberFormatException e) //Catch empty values
            {   
                msg("input values are invalid, please try again");
            }
            
            //Transfer user input to labels
            lblName.setText(userCar.getName());
            lblMake.setText(userCar.getMake());
            lblModel.setText(userCar.getModel());
            lblColor.setText(userCar.getColor());
            
            //Clear user input
            txtName.setText("");
            txtMake.setText("");
            txtModel.setText("");
            txtColor.setText("");

            //Display confirmation msg and enable controls
            msg("Welcome " + userCar.getName() + ", drive it like you stole it!!!" );
            btnCreateCar.setEnabled(false);
            btnGas.setEnabled(true);
            btnBrake.setEnabled(true);
            //Place focus on Accelate button
            btnGas.requestFocus();
        }
        else
        {
            msg("Please enter values for all fields!");
        }
    }//GEN-LAST:event_btnCreateCarActionPerformed

/**
******************************************************
***  Method Name: btnGasActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method clears any previous status msgs, checks to
*   see if a Car object has been created using the boolean
*   variable "userPresent" and if successful, calls the
*   Car object's accelerate method, incrementing the object's
*   speed property by 5.  The speed-o-meter is then updated
*   using the object's speed property.  Goofy messages are
*   sent to the user to enhance the user's experience.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
    
    private void btnGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGasActionPerformed
        // TODO add your handling code here:
        
        msg(""); //Clear previous messages
        if(userPresent != false)    //Check if user values are entered
        {
            userCar.accelerate();   //Add 5 to mph
            lblSpeed.setText(Integer.toString(userCar.speed));  //update speedometer
        }
        else
        {
            msg("Please enter car information to begin!");  //Prompt user to enter information
            txtName.requestFocus();
        }
        
        if(userCar.speed == 100)
        {
            msg("WHOOAA BUDDY, SLOW DOWN");  //GUI Feedback for entertainment purposes
        }
        
        if(userCar.speed > 100  && userCar.speed < 150)
        {
            msg("");  //Clear msg
        }
        
        if(userCar.speed > 150  && userCar.speed < 160)
        {
            msg("You're gonna hurt somebody now"); //GUI Feedback for entertainment purposes
        }
        
        if(userCar.speed > 165  && userCar.speed < 175)
        {
            msg("Ok, you've been warned");  //GUI Feedback for entertainment purposes
        }
    }//GEN-LAST:event_btnGasActionPerformed

/**
******************************************************
***  Method Name: btnBrakeActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method clears any previous status msgs, checks to
*   see if a Car object has been created using the boolean
*   variable "userPresent" and also if the Car object's
*   current speed is equal to 0.  If both these conditions are met,
*   then the program tells the user the car is stopped and
*   does perform anymore decrementing of the speed property.
*   If userPresent is true and the speed is higher than 0, then
*   the objects brake method is called, decrementing the speed by 5.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
    
    private void btnBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrakeActionPerformed
        // TODO add your handling code here:
        //Clear previous msg
        msg("");
        if(userPresent == true && userCar.speed == 0)   //check for user and if car is already stopped
        {
            msg("CAR IS STOPPED!");
        }
        else    //If moving, reduce by 5 mph
        {
            userCar.brake();
            lblSpeed.setText(Integer.toString(userCar.speed));
        }
    }//GEN-LAST:event_btnBrakeActionPerformed

/**
******************************************************
***  Method Name: btnCreateCarKeyPressed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the enter key event when
*   focus is on the create button.  When the button is
*   pressed, the method connected to the btnCreateCar control
*   is performed.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
   
    private void btnCreateCarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCreateCarKeyPressed
        // TODO add your handling code here:
        
        btnCreateCar.doClick(); //Respond to enter key and exec code to create car profile
        
    }//GEN-LAST:event_btnCreateCarKeyPressed

/**
******************************************************
***  Method Name: msg.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method serves as a short cut to updating the
*   status msg by accepting a string parameter value
*   and placing that value in the setText parameter of the
*   GUI's jLabel "lblStatusMsg".
* 
*   Method Inputs:
*   — One String variable
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
    
    private void msg(String lblMsg)
    {
        lblStatusMsg.setText(lblMsg);   //Populate status msg
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarGUI().setVisible(true);
            }
        });
    }
    
    Car userCar;                    //Create new Car var
    private String name;            //Var to hold car name
    private String make;            //var to hold car make
    private String model;           //var to hold car model
    private String color;           //var to hold car color
    private boolean userPresent = false;    //var to verify if all inputs are entered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrake;
    private javax.swing.JButton btnCreateCar;
    private javax.swing.JButton btnGas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblStatusMsg;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
