/**
******************************************************
***  Class Name: CarGUI.
***  Class Author:  Chris Lorenzo
******************************************************
* This class serves as the GUI to create and use
* objects from the car class.  It serves as a user
* interface to create and drive a car using built in
* controls.
******************************************************
*** Date: 13 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
package Lorenzo_Project1_ObjClsAttMeth;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author HR1
 */
public class CarGUI extends javax.swing.JFrame {

    /**
     * Creates new form CarGUI
     */
    public CarGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        btnCreateCar = new javax.swing.JButton();
        lblStatusMsg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGas = new javax.swing.JButton();
        btnBrake = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radButRed = new javax.swing.JRadioButton();
        radButOrange = new javax.swing.JRadioButton();
        radButBlue = new javax.swing.JRadioButton();
        radButBlack = new javax.swing.JRadioButton();
        radButGreen = new javax.swing.JRadioButton();
        radButYellow = new javax.swing.JRadioButton();
        btnColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOY RIDE - THE GAME");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("Joy Ride");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Create a car:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Make:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Model:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Color:");

        txtName.setNextFocusableComponent(txtMake);

        txtMake.setNextFocusableComponent(txtModel);

        txtModel.setNextFocusableComponent(radButRed);

        btnCreateCar.setText("Create Car");
        btnCreateCar.setNextFocusableComponent(txtName);
        btnCreateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCarActionPerformed(evt);
            }
        });
        btnCreateCar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCreateCarKeyPressed(evt);
            }
        });

        lblStatusMsg.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        lblStatusMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusMsg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Current Speed:");

        lblSpeed.setFont(new java.awt.Font("Tahoma", 0, 80)); // NOI18N
        lblSpeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpeed.setText("0");
        lblSpeed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("mph");

        btnGas.setBackground(new java.awt.Color(0, 204, 51));
        btnGas.setText("Accelerate");
        btnGas.setEnabled(false);
        btnGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGasActionPerformed(evt);
            }
        });

        btnBrake.setBackground(new java.awt.Color(255, 0, 0));
        btnBrake.setText("Brake");
        btnBrake.setEnabled(false);
        btnBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrakeActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Your Car:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Name:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Make:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Model:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Color:");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMake.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setNextFocusableComponent(btnCreateCar);

        radButRed.setText("Red");
        radButRed.setNextFocusableComponent(radButOrange);
        radButRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButRedActionPerformed(evt);
            }
        });

        radButOrange.setText("Orange");
        radButOrange.setNextFocusableComponent(radButBlue);
        radButOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButOrangeActionPerformed(evt);
            }
        });

        radButBlue.setText("Blue");
        radButBlue.setNextFocusableComponent(radButBlack);
        radButBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButBlueActionPerformed(evt);
            }
        });

        radButBlack.setText("Black");
        radButBlack.setNextFocusableComponent(radButGreen);
        radButBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButBlackActionPerformed(evt);
            }
        });

        radButGreen.setText("Green");
        radButGreen.setNextFocusableComponent(radButYellow);
        radButGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButGreenActionPerformed(evt);
            }
        });

        radButYellow.setText("Yellow");
        radButYellow.setNextFocusableComponent(btnCreateCar);
        radButYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButYellowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radButRed)
                    .addComponent(radButOrange)
                    .addComponent(radButBlue)
                    .addComponent(radButBlack)
                    .addComponent(radButGreen)
                    .addComponent(radButYellow))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radButRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radButOrange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radButBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radButBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radButGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radButYellow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblMake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCreateCar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(40, 40, 40)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel8)
                                        .addGap(67, 67, 67)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnGas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(10, 10, 10)
                                        .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMake, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblStatusMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(btnCreateCar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
******************************************************
***  Method Name: btnCreateCarActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method is responsible for taking the input value
*   from the user, converting them in String vars and then
*   sending those var to the Car's constructor as param values.
*   If successful, Car object is made, values are placed into
*   profile labels, input boxes are cleared, create button
*   is disabled, and brake and acceleration buttons are enabled.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
    
    private void btnCreateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCarActionPerformed
        // TODO add your handling code here:
        
        //Place user input into vars to instantiate a new Car object
        name = txtName.getText();
        make = txtMake.getText();
        model = txtModel.getText();

        //Test to ensure input values are not empty
        if(name.length() > 0 && make.length() > 0 && model.length() > 0 && color != null)
        {
                try
                {   
                    userCar = new Car(name, make, model, color);        //Send user input values to Car constructor
                    userPresent = true;                                 //If constructor succeeds, change boolean value to true for follow on tests

                    //Transfer user input to labels
                    lblName.setText(userCar.getName());
                    lblMake.setText(userCar.getMake());
                    lblModel.setText(userCar.getModel());
                    btnColor.setBackground(userCar.getColor());

                    //Clear user input
                    txtName.setText("");
                    txtMake.setText("");
                    txtModel.setText("");
                    
                    radButRed.setEnabled(false);
                    radButOrange.setEnabled(false);
                    radButBlue.setEnabled(false);
                    radButBlack.setEnabled(false);
                    radButGreen.setEnabled(false);
                    radButYellow.setEnabled(false);

                    //Display confirmation msg and enable controls
                    msg("Welcome " + userCar.getName() + ", drive it like you stole it!!!" );
                    btnCreateCar.setEnabled(false);
                    btnGas.setEnabled(true);
                    btnBrake.setEnabled(true);
                    //Place focus on Accelate button
                    btnGas.requestFocus();
                }
                catch (NumberFormatException e) //Catch empty values
                {   
                    msg("input values are invalid, please try again");
                }
        }
        else
        {
            msg("Please enter values for all fields!");
        }
    }//GEN-LAST:event_btnCreateCarActionPerformed

/**
******************************************************
***  Method Name: btnGasActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method clears any previous status msgs, checks to
*   see if a Car object has been created using the boolean
*   variable "userPresent" and if successful, calls the
*   Car object's accelerate method, incrementing the object's
*   speed property by 5.  The speed-o-meter is then updated
*   using the object's speed property.  Goofy messages are
*   sent to the user to enhance the user's experience.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/   
    private void btnGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGasActionPerformed
        // TODO add your handling code here:
        
        msg(""); //Clear previous messages
        if(userPresent != false)    //Check if user values are entered
        {
            userCar.accelerate();   //Add 5 to mph
            lblSpeed.setText(Integer.toString(userCar.speed));  //update speedometer
        }
        else
        {
            msg("Please enter car information to begin!");  //Prompt user to enter information
            txtName.requestFocus();
        }
        
        if(userCar.speed == 100)
        {
            msg("WHOOAA BUDDY, SLOW DOWN");  //GUI Feedback for entertainment purposes
        }
        
        if(userCar.speed > 100  && userCar.speed < 150)
        {
            msg("");  //Clear msg
        }
        
        if(userCar.speed > 150  && userCar.speed < 160)
        {
            msg("You're gonna hurt somebody now"); //GUI Feedback for entertainment purposes
        }
        
        if(userCar.speed > 165  && userCar.speed < 175)
        {
            msg("Ok, you've been warned");  //GUI Feedback for entertainment purposes
        }
        
        if(userCar.speed > 200)
        {
            msg("You're Nuts!!! Absolutely NUTTSSS!!!");  //GUI Feedback for entertainment purposes
        }     
        
    }//GEN-LAST:event_btnGasActionPerformed

/**
******************************************************
***  Method Name: btnBrakeActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method clears any previous status msgs, checks to
*   see if a Car object has been created using the boolean
*   variable "userPresent" and also if the Car object's
*   current speed is equal to 0.  If both these conditions are met,
*   then the program tells the user the car is stopped and
*   does perform anymore decrementing of the speed property.
*   If userPresent is true and the speed is higher than 0, then
*   the objects brake method is called, decrementing the speed by 5.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
    private void btnBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrakeActionPerformed
        // TODO add your handling code here:
        //Clear previous msg
        msg("");
        if(userPresent == true && userCar.speed == 0)   //check for user and if car is already stopped
        {
            msg("CAR IS STOPPED!");
        }
        else    //If moving, reduce by 5 mph
        {
            userCar.brake();
            lblSpeed.setText(Integer.toString(userCar.speed));
        }
    }//GEN-LAST:event_btnBrakeActionPerformed

/**
******************************************************
***  Method Name: btnCreateCarKeyPressed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the enter key event when
*   focus is on the create button.  When the button is
*   pressed, the method connected to the btnCreateCar control
*   is performed.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
    private void btnCreateCarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCreateCarKeyPressed
        // TODO add your handling code here:
        btnCreateCar.doClick(); //Respond to enter key and exec code to create car profile
    }//GEN-LAST:event_btnCreateCarKeyPressed

/**
******************************************************
***  Method Name: radButRedActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the user's selection via radio
*   button and calls the uncheckOtherButtons() method,
*   passing a string value of the color to use in the methods
*   switch statement to un-check all the other buttons.
*   This method also instantiates a new color object 
*   using the color values of the string representation,
*   and assigns it the color variable to pass to the constructor.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 19 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
    private void radButRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButRedActionPerformed
        // TODO add your handling code here:
        uncheckOtherButtons("Red");
        color = new Color(255,0,0);
    }//GEN-LAST:event_radButRedActionPerformed

/**
******************************************************
***  Method Name: radButOrangeActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the user's selection via radio
*   button and calls the uncheckOtherButtons() method,
*   passing a string value of the color to use in the methods
*   switch statement to un-check all the other buttons.
*   This method also instantiates a new color object 
*   using the color values of the string representation,
*   and assigns it the color variable to pass to the constructor.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 19 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
    private void radButOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButOrangeActionPerformed
        // TODO add your handling code here:
        uncheckOtherButtons("Orange");
        color = new Color(255,165,0);
    }//GEN-LAST:event_radButOrangeActionPerformed

/**
******************************************************
***  Method Name: radButBlueActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the user's selection via radio
*   button and calls the uncheckOtherButtons() method,
*   passing a string value of the color to use in the methods
*   switch statement to un-check all the other buttons.
*   This method also instantiates a new color object 
*   using the color values of the string representation,
*   and assigns it the color variable to pass to the constructor.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 19 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/
    private void radButBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButBlueActionPerformed
        // TODO add your handling code here:
        uncheckOtherButtons("Blue");
        color = new Color(0,0,255);
    }//GEN-LAST:event_radButBlueActionPerformed

/**
******************************************************
***  Method Name: radButBlackActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the user's selection via radio
*   button and calls the uncheckOtherButtons() method,
*   passing a string value of the color to use in the methods
*   switch statement to un-check all the other buttons.
*   This method also instantiates a new color object 
*   using the color values of the string representation,
*   and assigns it the color variable to pass to the constructor.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 19 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
    private void radButBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButBlackActionPerformed
        // TODO add your handling code here:
        uncheckOtherButtons("Black");
        color = new Color(0,0,0);
    }//GEN-LAST:event_radButBlackActionPerformed

/**
******************************************************
***  Method Name: radButGreenActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the user's selection via radio
*   button and calls the uncheckOtherButtons() method,
*   passing a string value of the color to use in the methods
*   switch statement to un-check all the other buttons.
*   This method also instantiates a new color object 
*   using the color values of the string representation,
*   and assigns it the color variable to pass to the constructor.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 19 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
    private void radButGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButGreenActionPerformed
        // TODO add your handling code here:
        uncheckOtherButtons("Green");
        color = new Color(0,255,0);
    }//GEN-LAST:event_radButGreenActionPerformed

/**
******************************************************
***  Method Name: radButYellowActionPerformed.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method responds to the user's selection via radio
*   button and calls the uncheckOtherButtons() method,
*   passing a string value of the color to use in the methods
*   switch statement to un-check all the other buttons.
*   This method also instantiates a new color object 
*   using the color values of the string representation,
*   and assigns it the color variable to pass to the constructor.
* 
*   Method Inputs:
*   — ActionEvent
*   Return Value:
*   — None
* 
******************************************************
*** Date: 19 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
    private void radButYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButYellowActionPerformed
        // TODO add your handling code here:
        uncheckOtherButtons("Yellow");
        color = new Color(255,255,0);
    }//GEN-LAST:event_radButYellowActionPerformed

    
/**
******************************************************
***  Method Name: uncheckOtherButtons.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method serves to un-check all other radio
*   buttons when the user makes a radio button selection,
*   using a switch statement.
* 
*   Method Inputs:
*   — One String var to hold the switch test value
*   Return Value:
*   — None
* 
******************************************************
*** Date: 19 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/     
    private void uncheckOtherButtons(String color)
    {
        
        switch (color)  {       //Perform selected statements when the case value matches the color var
            case "Red":
                radButOrange.setSelected(false);
                radButBlue.setSelected(false);
                radButBlack.setSelected(false);
                radButGreen.setSelected(false);
                radButYellow.setSelected(false);
                break;
            case "Orange":
                radButRed.setSelected(false);
                radButBlue.setSelected(false);
                radButBlack.setSelected(false);
                radButGreen.setSelected(false);
                radButYellow.setSelected(false);
                break;
            case "Blue":
                radButOrange.setSelected(false);
                radButRed.setSelected(false);
                radButBlack.setSelected(false);
                radButGreen.setSelected(false);
                radButYellow.setSelected(false);
                break;
            case "Black":
                radButOrange.setSelected(false);
                radButBlue.setSelected(false);
                radButRed.setSelected(false);
                radButGreen.setSelected(false);
                radButYellow.setSelected(false);
                break;
            case "Green":
                radButOrange.setSelected(false);
                radButBlue.setSelected(false);
                radButBlack.setSelected(false);
                radButRed.setSelected(false);
                radButYellow.setSelected(false);
                break;
            case "Yellow":
                radButOrange.setSelected(false);
                radButBlue.setSelected(false);
                radButBlack.setSelected(false);
                radButGreen.setSelected(false);
                radButRed.setSelected(false);
                break;
        }
        
    }
/**
******************************************************
***  Method Name: msg.
***  Method Author:  Chris Lorenzo
******************************************************
*   This method serves as a short cut to updating the
*   status msg by accepting a string parameter value
*   and placing that value in the setText parameter of the
*   GUI's jLabel "lblStatusMsg".
* 
*   Method Inputs:
*   — One String variable
*   Return Value:
*   — None
* 
******************************************************
*** Date: 14 September 2017
******************************************************
*** Changes: N/A
******************************************************
*/    
    
    private void msg(String lblMsg)
    {
        lblStatusMsg.setText(lblMsg);   //Populate status msg
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarGUI().setVisible(true);
            }
        });
    }
    
    Car userCar;                    //Create new Car var
    private String name;            //Var to hold car name
    private String make;            //var to hold car make
    private String model;                   //var to hold car model
    private boolean userPresent = false;    //var to verify if all inputs are entered
    private Color color;                    //Var to hold color selected by user to place in constructor

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrake;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnCreateCar;
    private javax.swing.JButton btnGas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblStatusMsg;
    private javax.swing.JRadioButton radButBlack;
    private javax.swing.JRadioButton radButBlue;
    private javax.swing.JRadioButton radButGreen;
    private javax.swing.JRadioButton radButOrange;
    private javax.swing.JRadioButton radButRed;
    private javax.swing.JRadioButton radButYellow;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
